import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "eCommerce Website",
  description: "Generated by L2Q1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
      <header                             //toutes les pages du site auront le meme header defini ici
          style={{
              backgroundColor: "lightgrey",
              padding: "1rem",
          }}>
      <p>Header</p>
      </header>
      {children}</body>
    </html>
  );
}
