import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "eCommerce Website",
  description: "Generated by L2Q1",
};

export default function RootLayout({ // toutes les pages du site auront la meme
  children,                          // mise en page (=layout) def ici
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    <html lang="fr">
    <body className={inter.className}>

    <header
        style={{
            backgroundColor: "white", // Modification de la couleur de fond
            padding: "1.3rem",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            border: "1px solid lightgrey", // Ajout d'une bordure grise
        }}>
        <div style={{
            width: "33%",
        }}>
            <a href="/"> {/* Lien vers la page d'accueil */}
                [Logo]
            </a>
        </div>
        <nav
            style={{
                display: "flex",
                alignItems: "center",
                flex: 0.8, // Pour étirer la barre de navigation et centrer les titres
                justifyContent: "space-around", // Pour espacer les éléments
            }}
        >
            <a href="/account">Mon Compte</a>
            <a href="/buy/products">Acheter</a>
            <a href="/contact">Contact</a>
            <a href="/about">À Propos</a>
        </nav>

        <div style={{
            display: "flex",
            alignItems: "center",
            width: "33%",
            justifyContent: "space-evenly",
        }}>

            <input style={{
                border: "1px solid lightgrey",
                borderRadius: 7,
                padding: 5,
                width: "50%",
            }}
                type="search"
                placeholder="Rechercher..."
            />


            <a href="/cart"> {/* Lien vers la page du panier */}
                <p>[Panier]</p>
            </a>
        </div>
    </header>

    {children}

    <footer
        style={{
            backgroundColor: "white", // Modification de la couleur de fond
            padding: "1.3rem",
            marginTop: "2rem",
            textAlign: "center",
            border: "1px solid lightgrey", // Ajout d'une bordure grise
        }}>
        <p>L2Q1 2023-2024 - Site de e-Commerce</p>
    </footer>

    </body>
    </html>
  );
}
