import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "eCommerce Website",
  description: "Generated by L2Q1",
};

export default function RootLayout({ // Toutes les pages du site auront la meme mise en page (=layout) defini ici
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    <html lang="fr">
    <body className={inter.className}>

    <header // Barre d'en-tête
        style={{
            backgroundColor: "white", // Modification de la couleur de fond
            padding: "1.3rem", // Ajout d'un remplissage de 1.3 rem
            display: "flex", // Utilisation de la disposition flexible
            justifyContent: "space-between", // Alignement des éléments avec un espace entre eux
            alignItems: "center", // Alignement vertical au centre des élément
            border: "1px solid lightgrey", // Ajout d'une bordure grise de 1 pixel
        }}>
        <div // Pour le logo qui redirige vers l'acceuil
            style={{
            width: "33%", // Largeur de la division à 33% de la largeur de son conteneur
        }}>
            <a href="/"> {/* Lien vers la page d'accueil */}
                [Logo]
            </a>
        </div>
        <nav //barre de navigation qui redirige vers la page souhaité
            style={{
                display: "flex",
                alignItems: "center",
                flex: 0.8, // Pour étirer la barre de navigation et centrer les titres
                justifyContent: "space-around", // Pour espacer les éléments de manière égale
            }}
        >
            <a href="/account">Mon Compte</a>
            <a href="/buy/products">Acheter</a>
            <a href="/contact">Contact</a>
            <a href="/about">À Propos</a>
        </nav>

        <div style={{
            display: "flex",
            alignItems: "center",
            width: "33%",
            justifyContent: "space-evenly",
        }}>

            <input // Champ de recherche pour la barre e recherche
                style={{
                border: "1px solid lightgrey",
                borderRadius: 7, // Ajout d'un rayon de bordure de 7 pixels pour arrondir les coins
                padding: 5, // Ajout d'un remplissage intérieur de 5 pixels
                width: "50%", // Définit la largeur de l'élément input à 50% de la largeur de son conteneur
            }}
                type="search" // Type de champ de recherche
                placeholder="Rechercher..." // Texte de l'indicateur de champ de recherche
            />


            <a href="/cart"> {/* Lien vers la page du panier */}
                <p>[Panier]</p>
            </a>
        </div>
    </header>

    {children}

    <footer // Pied de page
        style={{
            backgroundColor: "white",
            padding: "1.3rem",
            marginTop: "2rem", // Ajout d'une marge supérieure de 2 rem
            textAlign: "center",
            border: "1px solid lightgrey",
        }}>
        <p>L2Q1 2023-2024 - Site de e-Commerce</p>
    </footer>

    </body>
    </html>
  );
}
